### ISSUE TITLE
Issue with Assigning Roots to Verse

### ISSUE THREAD

**Issue by AliAmmarAwan** [AliAmmarAwan/LAB_11#1] opened 2023-11-02 09:28 UTC
1. Navigate to the "Assign Roots" feature in the GUI.
2. Select a verse and attempt to assign roots.
3. Observe the outcome.

Expected Behavior: The selected roots should be successfully assigned to
the verse without any errors.

Actual Behavior: There is an issue with the roots not being assigned
correctly, and the system is not reflecting the changes.

Additional Context: This is a critical functionality for our project, and
the incorrect assignment of roots is affecting the accuracy of our data.

**Comment by AbdulBasit120** [comment] 2023-11-02 09:30
2. Issue for f219418: Assign Roots to Verse in GUI

Title: Issue with Assigning Roots to Verse

Comment: When attempting to assign roots to a verse in the GUI, I
encountered unexpected behavior. Here are the details:

Steps to Reproduce:

   1. Navigate to the "Assign Roots" feature in the GUI.
   2. Select a verse and attempt to assign roots.
   3. Observe the outcome.

Expected Behavior: The selected roots should be successfully assigned to
the verse without any errors.

Actual Behavior: There is an issue with the roots not being assigned
correctly, and the system is not reflecting the changes.

Additional Context: This is a critical functionality for our project, and
the incorrect assignment of roots is affecting the accuracy of our data.

Labels:

   - bug
   - enhancement
   - GUI

Assignees:

   - f219418

Project:

   - GUI Development Board

**Comment by AbdulBasit120** [comment] 2023-11-02 09:44
just wanted to drop by and say how impressed I am with the hard work you're putting into our project. Your dedication is truly inspiring! Remember, every late night, every challenge you overcome, and every breakthrough you make is a step closer to turning our project into something amazing.

Your efforts are not only shaping the success of our project but are a testament to your commitment and passion. Keep pushing your limits because I believe in your abilities and know that you're capable of achieving great things. Remember, the journey may be tough, but the destination will be worth it.

You've got this! 💪 Let's continue to make strides together and create something we can all be proud of.

Cheers to your hard work and determination! 🌟

**Comment by AbdulBasit120** [comment] 2023-11-02 09:45
sir?? Are we going to start today!! Rn!!!!!

**Comment by AliAmmarAwan** [comment] 2023-11-02 09:47
yes! you have to complete it till 4:45Pm today (NOV 2,2023)

**Comment by AbdulBasit120** [comment] 2023-11-02 09:47
ok

**Comment by AliAmmarAwan** [comment] 2023-11-02 11:38
COMPLETE

**Closed as completed** 2023-11-02 11:38 UTC
Labels: bug, enhancement, GUI
